# Базовые структуры данных



## Домашнее задание 

### Описание домашнего задания и формат сдачи

В домашнем задании необходимо решить предложенные задачи по программированию – вписать свой код в ячейки после условий задач вместо комментария `### YOUR CODE HERE ###` в файле *jun_anl_data_structures.ipynb* и сохранить изменения, используя опцию *Save and Checkpoint* из вкладки меню *File* или кнопку *Save and Checkpoint* на панели инструментов. Итоговый файл в формате `.ipynb` (файл Jupyter Notebook) необходимо загрузить в личный кабинет обучающей онлайн платформы Skillbox (https://go.skillbox.ru/) и отправить на проверку.

**NB!** Во всех заданиях обязательно наличие выдачи.

## Индексация списка

In [0]:
L = [[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]], 
    [[21, 22, 23, 24, 25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]], 
    [[41, 42, 43, 44, 45], [46, [47, 48], 49, 50], [51, 52, 53, 54, 55], [56, 57, 58, 59, 60]], 
    [61, 62, 63, [64, 65, 66, 67, 68, 69, 70, 71], 72, 73, 74, [75, [76, 77, 78], 79], 80], 
    [81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]]

### 1.
Из приведенного выше списка списков выведите с помощью индексов число `7`.

In [2]:
L = [[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]], 
    [[21, 22, 23, 24, 25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]], 
    [[41, 42, 43, 44, 45], [46, [47, 48], 49, 50], [51, 52, 53, 54, 55], [56, 57, 58, 59, 60]], 
    [61, 62, 63, [64, 65, 66, 67, 68, 69, 70, 71], 72, 73, 74, [75, [76, 77, 78], 79], 80], 
    [81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]]
L[0][0][6]

7

### 2.
Из приведенного выше списка списков выведите с помощью индексов число `49`.

In [3]:
L = [[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]], 
    [[21, 22, 23, 24, 25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]], 
    [[41, 42, 43, 44, 45], [46, [47, 48], 49, 50], [51, 52, 53, 54, 55], [56, 57, 58, 59, 60]], 
    [61, 62, 63, [64, 65, 66, 67, 68, 69, 70, 71], 72, 73, 74, [75, [76, 77, 78], 79], 80], 
    [81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]]
L[2][1][2]

49

### 3.
Из приведенного выше списка списков выведите с помощью индексов число `78`.

In [4]:
L = [[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]], 
    [[21, 22, 23, 24, 25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]], 
    [[41, 42, 43, 44, 45], [46, [47, 48], 49, 50], [51, 52, 53, 54, 55], [56, 57, 58, 59, 60]], 
    [61, 62, 63, [64, 65, 66, 67, 68, 69, 70, 71], 72, 73, 74, [75, [76, 77, 78], 79], 80], 
    [81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]]
L[3][7][1][2]

78

### 4.
Из приведенного выше списка списков выведите с помощью индексов (используя **отрицательные значения**) число `99`.

In [5]:
L = [[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]], 
    [[21, 22, 23, 24, 25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]], 
    [[41, 42, 43, 44, 45], [46, [47, 48], 49, 50], [51, 52, 53, 54, 55], [56, 57, 58, 59, 60]], 
    [61, 62, 63, [64, 65, 66, 67, 68, 69, 70, 71], 72, 73, 74, [75, [76, 77, 78], 79], 80], 
    [81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]]
L[-1][-2]

99

### 5.
Из приведенного выше списка списков сделайте **срез** с числом `74`.

In [6]:
L = [[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]], 
    [[21, 22, 23, 24, 25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]], 
    [[41, 42, 43, 44, 45], [46, [47, 48], 49, 50], [51, 52, 53, 54, 55], [56, 57, 58, 59, 60]], 
    [61, 62, 63, [64, 65, 66, 67, 68, 69, 70, 71], 72, 73, 74, [75, [76, 77, 78], 79], 80], 
    [81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]]
L[3:4]
L[3][6]

74

### 6.
Из приведенного выше списка списков сделайте **срез** с числами `47, 48`.

In [7]:
L = [[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]], 
    [[21, 22, 23, 24, 25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]], 
    [[41, 42, 43, 44, 45], [46, [47, 48], 49, 50], [51, 52, 53, 54, 55], [56, 57, 58, 59, 60]], 
    [61, 62, 63, [64, 65, 66, 67, 68, 69, 70, 71], 72, 73, 74, [75, [76, 77, 78], 79], 80], 
    [81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]]
L[2:3]
L[2][1][1]

[47, 48]

### 7.
Из приведенного выше списка списков сделайте **срез** с числами `77, 78`.

In [8]:
L = [[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]], 
    [[21, 22, 23, 24, 25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]], 
    [[41, 42, 43, 44, 45], [46, [47, 48], 49, 50], [51, 52, 53, 54, 55], [56, 57, 58, 59, 60]], 
    [61, 62, 63, [64, 65, 66, 67, 68, 69, 70, 71], 72, 73, 74, [75, [76, 77, 78], 79], 80], 
    [81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]]
L[3:4]
L[3][7][1][1:3]

[77, 78]

## Функция range()

### 8.
С помощью функции `range` сгенерируйте следующую последовательность: <br>
`[0, 1, 2, 3, 4]`

In [9]:
list(range(5))

[0, 1, 2, 3, 4]

### 9.
С помощью функции `range` сгенерируйте следующую последовательность: <br>
`[3, 4]`

In [10]:
list(range(3,5))

[3, 4]

### 10.
С помощью функции `range` сгенерируйте следующую последовательность: <br>
`[4, 8, 12, 16]`

In [11]:
list(range(4,20,4))

[4, 8, 12, 16]

### 11.
С помощью функции `range` сгенерируйте следующую последовательность: <br>
`[16, 12, 8, 4]`

In [12]:
list(range(16,1,-4))

[16, 12, 8, 4]

### 12.
С помощью функции `range` сгенерируйте следующую последовательность: <br>
`[0, 5, 10]`

In [13]:
list(range(0,11,5))

[0, 5, 10]

### 13.
С помощью функции `range` сгенерируйте следующую последовательность: <br>
`[10, 5, 0]`

In [14]:
list(range(10,-1,-5))

[10, 5, 0]

### 14.
С помощью функции `range` сгенерируйте следующую последовательность: <br>
`[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1]`

In [15]:
list(range(-10,0,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1]

### 15.
С помощью функции `range` сгенерируйте следующую последовательность: <br>
`[-10, -16, -22, -28, -34]`

In [16]:
list(range(-10,-35,-6))

[-10, -16, -22, -28, -34]

## Операторы и типы данных

Этот блок должен быть решен **БЕЗ** использования готовых функций и сторонних библиотек. Используйте операторы.

### 16.
Часы показывают время в формате h:mm:ss (количество часов (от 0 до 23), двузначное количество минут, двузначное количество секунд). Количество минут и секунд при необходимости дополняются до двузначного числа нулями.

Программа должна запрашивать количество секунд S, которое прошло с начала суток, и выводить в формате h:mm:ss, какое время будут показывать часы. <br><br>

*Формат ввода:* <br>
3600<br><br>

*Формат вывода:* <br>
1:00:00

In [1]:
n = int(input())
sec = (n // 1) % 60
minutes = (n // 60) % 60
hour = int((n // 3600) % 24)
t = str(hour)+ ':' + str(minutes)+':' + str(sec)
t

3600

'1:0:0'

### 17.
Машина выезжает на нулевой километр МКАД и едет по часовой стрелке с постоянной скоростью V километров в час. На каком километре МКАД машина окажется через T часов? 
<br> Длина МКАД: 109 км. <br><br> 

*Формат ввода:* <br>
60 <br>
1
<br><br>
*Формат вывода:* <br>
60

In [2]:
speed = int(input('Введите скорость машины (km/h.):'))
time = int(input('Введите время в пути (час.):'))
distance = speed * time % 109
distance

Введите скорость машины (km/h.):60
Введите время в пути (час.):1

60

### 18.
Напишите программу, которая запрашивает целое пятизначное число и выводит сумму его цифр.

*Формат ввода:* <br>
11111
<br><br>
*Формат вывода:* <br>
5

In [3]:
n= input('Введите пятизначное число:')
a = int(n[0])
b = int(n[1])
c = int(n[2])
d = int(n[3])
e = int(n[4])
summ = a+b+c+d+e
summ

Введите пятизначное число:11111

5

### 19.
Напишите программу, которая запрашивает целое четырехзначное число и меняет местами его две первые и две последние цифры.

*Формат ввода:* <br>
5236 
<br><br>
*Формат вывода:* <br>
3652

In [4]:
n = input('Введите целое четырехзначное число:')
a = int(n[0])
b = int(n[1])
c = int(n[2])
d = int(n[3])
str(c) + str(d) + str (a) + str(b)

Введите целое четырехзначное число:5236

'3652'

### 20.
Напишите программу, которая на основании параметра D (сколько километров в день преодолевает машина), расчитывает сколько дней она затратит на путь длиной P километров.  <br><br>
*Формат ввода:* <br>
105 <br>
120
<br><br>
*Формат вывода:* <br>
2

In [5]:
D = int(input('Введите сколько километров в день преодолевает машина:'))
P = int(input('Введите длину пути:'))
T = (P+D)//D
T

Введите сколько километров в день преодолевает машина:105
Введите длину пути:120

2

### 21.
Напишите программу, которая считает, сколько рублей и копеек нужно заплатить за N авокадо, если один авокадо стоит R рублей и K копеек. <br><br>
*Формат ввода:* <br>
40 20 <br>
5
<br><br>
*Формат вывода:* <br>
201 руб. 00 коп.

In [6]:
rub,cop = input('Введите стоимость одного авокадо R и K:').split( )
avokado = int(input('Введите необходимое количество авокадо:'))
summrub = (int(rub) * avokado)+ 1
summcop =  + (int(cop) * avokado) % 100
print('Итоговая сумма: ', summrub , 'руб.', summcop, 'коп.' )

Введите стоимость одного авокадо R и K:40 20
Введите необходимое количество авокадо:5
Итоговая сумма:  201 руб. 0 коп.

### 22.
Пусть организаторы мероприятия неправильно составили гугл-форму и просили людей указывать ФИО в неправильном порядке. Сначала спрашивали имя, потом отчество, затем фамилию. Напишите программу, которая будет переставлять ФИО в нужный порядок. <br> <br> 

*Формат ввода:* <br>
Иван Иванович Иванов<br><br>
*Формат вывода:* <br>
Иванов Иван Иванович

In [7]:
name,fathername,surname = input('Введите Имя Отчество Фамилию: ').split( )
surname,name,fathername

Введите Имя Отчество Фамилию: Иван Иванович Иванов

('Иванов', 'Иван', 'Иванович')

## Cловари и списки

### 23.
У вас есть список с заказом в ресторане. Напишите программу, которая меняет указанное по названию блюдо на другое. При этом новое блюдо в списке будет расположено на месте того, что было заменено.

*Формат ввода:* <br>
белое вино<br>
красное вино <br><br>
*Формат вывода:* <br>
`['красное вино', 'салат Цезарь', 'паста Карбонара', 'чизкейк', 'шоколадный сорбет']`

In [ ]:
order = ['белое вино', 'салат Цезарь', 'паста Карбонара', 'чизкейк', 'шоколадный сорбет']

In [8]:
wine = input('Введите желаемое вино: ')
order = [wine, 'салат Цезарь', 'паста Карбонара', 'чизкейк', 'шоколадный сорбет']
str(order)

Введите желаемое вино: белое вино

"['белое вино', 'салат Цезарь', 'паста Карбонара', 'чизкейк', 'шоколадный сорбет']"

__________________
Вам дан словарь c расписанием на неделю.

In [ ]:
diary = {'понедельник': {
                          'утро': ['погулять с собакой'],
                          'день': [],
                          'вечер': ['погулять с собакой']
                                      },
        'вторник': {
                          'утро': ['погулять с собакой'],
                          'день': [],
                          'вечер': ['погулять с собакой']
                                      },
        'среда': {
                          'утро': ['погулять с собакой'],
                          'день': [],
                          'вечер': ['погулять с собакой']
                                      },
        'четверг': {
                          'утро': ['погулять с собакой'],
                          'день': [],
                          'вечер': ['погулять с собакой']
                                      },
        'пятница': {
                          'утро': ['заехать в шиномонтаж', 'помыть машину'],
                          'день': [],
                          'вечер': ['поход в театр',  'ужин в кафе']
                                      },
        'суббота': {
                          'утро': [],
                          'день': [],
                          'вечер': []
                                      },
        'воскресенье': {
                          'утро': [],
                          'день': [],
                          'вечер': []
                                      }}

### 24.
Удалите ключи `суббота` и `воскресенье`. Вместо них добавьте пару, где ключ это кортеж `суббота, воскресенье`, а значение – список с делом `посадить цветы на даче`. Можно ли сделать ключ `суббота, воскресенье` списком?

In [9]:
diary = {'понедельник': {
                          'утро': ['погулять с собакой'],
                          'день': [],
                          'вечер': ['погулять с собакой']
                                      },
        'вторник': {
                          'утро': ['погулять с собакой'],
                          'день': [],
                          'вечер': ['погулять с собакой']
                                      },
        'среда': {
                          'утро': ['погулять с собакой'],
                          'день': [],
                          'вечер': ['погулять с собакой']
                                      },
        'четверг': {
                          'утро': ['погулять с собакой'],
                          'день': [],
                          'вечер': ['погулять с собакой']
                                      },
        'пятница': {
                          'утро': ['заехать в шиномонтаж', 'помыть машину'],
                          'день': [],
                          'вечер': ['поход в театр',  'ужин в кафе']
                                      },
        'суббота': {
                          'утро': [],
                          'день': [],
                          'вечер': []
                                      },
        'воскресенье': {
                          'утро': [],
                          'день': [],
                          'вечер': []
                                      }}
diary.pop ('суббота','воскресенье')

holidays = {'суббота':'посадить цветы на даче','воскресенье':'посадить цветы на даче'}
diary.update(holidays)
diary

{'понедельник': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'вторник': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'среда': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'четверг': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'пятница': {'утро': ['заехать в шиномонтаж', 'помыть машину'],
  'день': [],
  'вечер': ['поход в театр', 'ужин в кафе']},
 'воскресенье': 'посадить цветы на даче',
 'суббота': 'посадить цветы на даче'}

### 25.
Добавьте в список дел во вторник утром `поход к зубному`.

In [10]:
diary = {'понедельник': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'вторник': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'среда': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'четверг': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'пятница': {'утро': ['заехать в шиномонтаж', 'помыть машину'],
  'день': [],
  'вечер': ['поход в театр', 'ужин в кафе']},
 'воскресенье': 'посадить цветы на даче',
 'суббота': 'посадить цветы на даче'}
tuesday = {'вторник': {
                          'утро': ['поход к зубному'],
                          'день': [],
                          'вечер': ['погулять с собакой']
                                      }}
diary.update(tuesday)
diary

{'понедельник': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'вторник': {'утро': ['поход к зубному'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'среда': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'четверг': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'пятница': {'утро': ['заехать в шиномонтаж', 'помыть машину'],
  'день': [],
  'вечер': ['поход в театр', 'ужин в кафе']},
 'воскресенье': 'посадить цветы на даче',
 'суббота': 'посадить цветы на даче'}

### 26.
Замените `поход в театр` на `поход в кино` в списке дел в пятницу вечером.

In [11]:
diary = {'понедельник': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'вторник': {'утро': ['поход к зубному'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'среда': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'четверг': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'пятница': {'утро': ['заехать в шиномонтаж', 'помыть машину'],
  'день': [],
  'вечер': ['поход в театр', 'ужин в кафе']},
 'воскресенье': 'посадить цветы на даче',
 'суббота': 'посадить цветы на даче'}
firthday =  {'пятница': {'утро': ['заехать в шиномонтаж', 'помыть машину'],
  'день': [],
  'вечер': ['поход в кино', 'ужин в кафе']}}
diary.update(firthday)
diary

{'понедельник': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'вторник': {'утро': ['поход к зубному'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'среда': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'четверг': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'пятница': {'утро': ['заехать в шиномонтаж', 'помыть машину'],
  'день': [],
  'вечер': ['поход в кино', 'ужин в кафе']},
 'воскресенье': 'посадить цветы на даче',
 'суббота': 'посадить цветы на даче'}

### 27.
Ваш друг вернется из отпуска на один день раньше, поэтому он заберет свою собаку в среду, а не в четверг. Удалите дело `погулять с собакой` из соответствующих списков.

In [12]:
diary = {'понедельник': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'вторник': {'утро': ['поход к зубному'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'среда': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'четверг': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'пятница': {'утро': ['заехать в шиномонтаж', 'помыть машину'],
  'день': [],
  'вечер': ['поход в кино', 'ужин в кафе']},
 'воскресенье': 'посадить цветы на даче',
 'суббота': 'посадить цветы на даче'}
wednesday = {'четверг': {'утро': [],
  'день': [],
  'вечер': []},
 'пятница': {'утро': ['заехать в шиномонтаж', 'помыть машину'],
  'день': [],
  'вечер': ['поход в кино', 'ужин в кафе']},
 'воскресенье': 'посадить цветы на даче',
 'суббота': 'посадить цветы на даче'}
diary.update(wednesday)
diary

{'понедельник': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'вторник': {'утро': ['поход к зубному'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'среда': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'четверг': {'утро': [], 'день': [], 'вечер': []},
 'пятница': {'утро': ['заехать в шиномонтаж', 'помыть машину'],
  'день': [],
  'вечер': ['поход в кино', 'ужин в кафе']},
 'воскресенье': 'посадить цветы на даче',
 'суббота': 'посадить цветы на даче'}

### 28.
Выведите второе дело из списка дел, которые вам нужно сделать в пятницу утром.

In [13]:
diary = {'понедельник': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'вторник': {'утро': ['поход к зубному'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'среда': {'утро': ['погулять с собакой'],
  'день': [],
  'вечер': ['погулять с собакой']},
 'четверг': {'утро': [], 'день': [], 'вечер': []},
 'пятница': {'утро': ['заехать в шиномонтаж', 'помыть машину'],
  'день': [],
  'вечер': ['поход в кино', 'ужин в кафе']},
 'воскресенье': 'посадить цветы на даче',
 'суббота': 'посадить цветы на даче'}
diary["пятница"]["утро"][1]

'помыть машину'