## Подготовка данных

In [96]:
import re

import pandas as pd
import pymorphy2


text_df = pd.read_csv("D:/DZ/content_description.csv", sep='\t')
text_df.head()

# разбиваем тест на слова
corpus = []
# регулярка для поиска слов
regular_expr = r'\w+'
reg_expr_compiled = re.compile(regular_expr)
# формируем датасет из отдельных слов
for raw_text in text_df.description.values:
    # приводим к нижнему регистру
    raw_text_lower = raw_text.lower()
    # разбиваем текст на слова
    text_by_words = reg_expr_compiled.findall(raw_text_lower) 
    corpus.append(text_by_words)

# нормализация текста
normalized_corpus = []
morph = pymorphy2.MorphAnalyzer()
# нормализуем каждое слово в тексте
for token_list in corpus:
    normalized_token_list = []
    for word in token_list:
        parsed_token = morph.parse(word)
        normal_form = parsed_token[0].normal_form
        normalized_token_list.append(normal_form)
    normalized_corpus.append(normalized_token_list)

# превращаем в DataFrame
doc_count = len(normalized_corpus)
doc_ids = []
tokens = []
# формируем два списка-колонки датафрейма
for doc_id in range(doc_count):
    for token in normalized_corpus[doc_id]:
        doc_ids.append(doc_id)
        tokens.append(token)

tokens_df = pd.DataFrame({
    'doc_id': doc_ids,
    'word': tokens
})
# дамми-столбец
tokens_df = tokens_df.assign(dummy = 1)
# аггрегируем статистики
word_count_df = tokens_df.groupby(['doc_id','word'])['dummy'].count().reset_index()

data = word_count_df[word_count_df.doc_id==0].sort_values(by='dummy', ascending=False)
data

     doc_id       word  dummy
6         0          в     10
29        0          и      7
37        0    который      5
111       0     шерлок      4
77        0          с      4
..      ...        ...    ...
39        0  культовый      1
38        0      кроме      1
36        0    котелок      1
35        0     костюм      1
114       0       этот      1

[115 rows x 3 columns]

# 10.3  Домашняя работа

10.3.1 **Задание простого уровня** Для каждого слова подсчитайте процент документов, в которых содержится это слово. Сформируйте dataframe doc_frequency. Процен документов вычисляется по формуле
$$
d = \frac{m}{n} \times 100
$$
где $m$ - количество документов, в которых встретилось это слово, а $n$ - общее количество документов. Значение в процентах округлите до целых.

Посмотрите какие слова оказались в топе - это предлоги и частицы. Такие слова присутствуют во всех документах, а значит, их можно удалить из текста, чтобы оставшиеся слова были более "осмысленными". Это упростит анализ текста.

In [94]:
doc_frequency = pd.DataFrame()

doc_frequency = word_count_df.groupby('word')['doc_id'].count(
    ).reset_index(name='doc_freq').sort_values(
    by='doc_freq', ascending=False)

doc_frequency.doc_freq/=float(doc_count)

doc_frequency.head(10)

       word  doc_freq
171       и     1.000
41        в     1.000
269      на     0.875
468       с     0.875
323      он     0.750
480    свой     0.750
618     что     0.750
326  онлайн     0.750
283      не     0.750
90      год     0.625

10.3.2 **Задание среднего уровня**

Воспользуйтесь регулярными выражениями, чтобы извлечь из текста все пары **имя+фамилия**.

* неформальное описание регулярки: пара слов идущая друг за другом, каждое из которых начинается с заглавной буквы
* анализировать нужно только `doc_id=3`
* текст берём из исходного датафрейма `text_df`
* заглавная буква в русскоязычном тексте соответствует символьному классу `r'[A-Я]*'`

In [3]:

raw_text = text_df.description.values[3]
# регулярка - её нужно поправить
reg_expr = r' [A-Я]\w+ [A-Я]\w+'
# компилируем регулярное выражение
reg_expr_compiled = re.compile(reg_expr)
# применяем выражение к тексту
for g in reg_expr_compiled.findall(raw_text):
    print(g)

 Стивена Фрая
 Джоном Дженксом
 Теда Уоллеса
 Теперь Тед
 Вскоре Тед

10.3.3 **Задание сложного уровня**. Словарь `genre_dict` содержит слова, которые являются характерными для того или иного жанра. Пользуясь словарём, а так же таблицей `word_count_df`, сформируйте таблицу двумя колонками `doc_id | genre` с жанрами фильмов.

Для этого нужно
* превратить словарь `genre_dict` в DataFrame формата `word | genre`
* соединить полученный датафрейм с помощью функции `merge` c ранее полученным датафреймом `word_count_df`, котороый содержит распределение слов по документам. Воспользуйтесь методом соединения `inner`
* для каждого документа выбрать жанр документа - это совокупность жанров слов отдельных слов. У одного контента может быть несколько жанров

In [91]:
import itertools
import pandas as pd

genre_dict = {
    'комедия': ['сатирический', 'авантюрный', 'забавный'],
    'мелодрама': ['выбор', 'позор', 'интрига'],
    'сказка': ['приключения', 'милый', 'семейный'],
    'детектив': ['тайна', 'разгадать', 'загадочный'], 
    'триллер': ['ужас', 'зловещий', 'нерв']
}

nested_genres =[[(i, j) for j in genre_dict[i]] for i in genre_dict]
# переводим из словаря к более удобному виду
flatten_genres = list(itertools.chain(*nested_genres))
# создаём DataFrame
genres_df = pd.DataFrame(flatten_genres, columns = ['genre', 'character_word'])


genre_dict_df = pd.DataFrame([[k,x] for k,v in genre_dict.items() for x in v], 
                  columns=['genre','word'])
doc_to_genres = pd.DataFrame()
new_df = genres_df.merge(genre_dict_df)
newest_df = new_df.merge(word_count_df, on = 'word', how = 'inner')
newest_df[['genre', 'word']].drop_duplicates()

        genre          word
0     комедия  сатирический
3     комедия    авантюрный
6     комедия      забавный
9   мелодрама         выбор
12  мелодрама         позор
15     сказка         милый
18   детектив         тайна
21   детектив     разгадать
24   детектив    загадочный
27    триллер          ужас
33    триллер      зловещий
36    триллер          нерв